### ISSUE TITLE
You have to update visibility_detector version. Have compilation error after flutter updated.

### ISSUE THREAD

**Issue by eul** [EdsonBueno/focus_detector#7]
visibility_detector-0.2.0/lib/src/visibility_detector_layer.dart:276:21: Error: Too many positional arguments: 1 allowed, but 2 found.
Try removing the extra positional arguments.
    super.addToScene(builder, layerOffset);

**Comment by rorystephenson** [comment]
Looks like it's as simple as bumping the version of the `visibility_detector` package which this package uses (there is a PR already... #6). For now you can add the following to your pubspec.yaml to avoid the error:

```yaml
dependency_overrides:
  visibility_detector: ^0.2.2
```

**Comment by EdsonBueno** [comment]
This is now solved in version **2.0.1**.
